---
- name: Provision VM
  hosts: all
  gather_facts: true
  become: true

  # Vagrant provison runs this file, so you don't actually need an inventory
  # it does that for you.
  # Basically we setup a bunch of environment stuff so we can ssh into the host
  # Using all the data from all.yml

  tasks:
    - name: Create user var
      ansible.builtin.set_fact:
        home_user: "{{ lookup('env', 'HOME') }}"
    - name: Allow password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication yes"
        state: present
      notify: restart sshd

    - name: Set authorized key took from file
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '{{ home_user }}/.ssh/id_rsa.pub') }}"

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
